[package]
edition = "2024"
name = "wasm"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
ndarray = "0.16.1"
rayon = "1.10.0"
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.100"
wasm-bindgen-rayon = "1.3.0"
