[package]
edition = "2024"
name = "wasm"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
either = "1.14.0"
num = { version = "0.4.3", features = ["num-bigint"] }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.100"
