export const COLOURS = {
    'dark': {
        cmy: [
            '#00ffff',
            '#ff00ff',
            '#ffff00',
            '#ff0000',
            '#00ff00',
            '#0000ff',
        ],
        rgb: [
            '#ff0000',
            '#00ff00',
            '#0000ff',
            '#00ffff',
            '#ff00ff',
            '#ffff00',
        ],
        rby: [
            '#ff0000',
            '#0000ff',
            '#ffff00',
            '#ff00ff',
            '#00ffff',
            '#00ff00',
        ],
    },
    'light': {
        cmy: [
            '#00ffff',
            '#ff00ff',
            '#ffff00',
            '#ff0000',
            '#00ff00',
            '#0000ff',
        ],
        rgb: [
            '#ff0000',
            '#00ff00',
            '#0000ff',
            '#00ffff',
            '#ff00ff',
            '#ffff00',
        ],
        rby: [
            '#ff0000',
            '#0000ff',
            '#ffff00',
            '#ff00ff',
            '#00ffff',
            '#00ff00',
        ],
    },
} as const;

export const HIGHLIGHT_COLOURS = [
    'darkblue',
    'black',
    'brown',
    'chocolate',
    'darkcyan',
    'purple',
    'deepskyblue',
    'gray',
    'indigo',
    'lavender',
    'lightsalmon',
    'lime',
    'orange',
    'orangered',
    'rebeccapurple',
    'silver',
    'slateblue',
    'violet',
    'white',
    'yellowgreen',
];